apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: ev_user
    database: ev_coorp
    secureJsonData:
      password: ev_password
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      database: ev_coorp
      postgresDefaultSchema: ocpp
      # Ensure database is set in both places for compatibility
      defaultDatabase: ev_coorp
    editable: true
