apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ev_coorp
    user: ev_user
    secureJsonData:
      password: ev_password
    jsonData:
      sslmode: disable
      postgresVersion: 1400
    editable: true
